version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws ecr get-login-password --region us-east-1 | docker login --username $ECR_LOGIN_USER --password-stdin $ECR_LOGIN_PASS
      - REPOSITORY_URI=$REPO_URL
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on date
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"main-service","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

cache:
  paths:
    - '/root/.docker/cli-plugins'
    - '/root/.npm//*'
    - 'dist//*'