version: "3"
services:

  imbayzid-ms:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: imbayzid-ms
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env