name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for 10 seconds
        run: sleep 10s

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PM2
        run: npm install -g pm2

      - name: Install dependencies
        run: npm install

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/mymakan-backend/mymakan-backend
            git pull origin main
            source ~/.nvm/nvm.sh
            nvm use 20
            npm install
            npm build
            $(which pm2) reload all
            $(which pm2) restart all
